name: Krew Release

on:
  push:
    tags:
      - 'v*'

jobs:
  krew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: rajatjindal/krew-release-bot@v0.0.44
        with:
          manifestFile: .krew.yaml
