name: Krew Release

on:
  push:
    tags:
      - 'v*'

jobs:
  krew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: rajatjindal/krew-release-bot@v0.0.44
        with:
          krew_template_file: .krew.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

